### ISSUE TITLE
MOD DOES NOT WORK FOR ME I FOLLOWED ALL INSTUCTIONS

### ISSUE THREAD

**Issue by KingOreoTheThird** [GlitchyTurtle/Avatar-Addon#10]
Upon entering the game with the mod installed, the message "you have your bending now (Arrows not in offhand)" appears, but there are no visible scrolls or related items in the inventory. I have tried multiple versions of the mod (1.20 and 1.19) from different sources, including a YouTube tutorial, with the same result. Notably, an enchanted book called "Bending Resistance" is present in the creative menu. It's important to note that I am using Minecraft Education Edition, and all other Bedrock mods are functioning correctly.

**Comment by KingOreoTheThird** [comment]
also commands are not working i copy pasted

**Comment by GlitchyTurtle** [comment]
What in the chatGPT? 😭
The only released downloadable version unless you package it yourself is on the [discord server](https://discord.gg/M4xxbhzEWU).

**Comment by KingOreoTheThird** [comment]
> What in the chatGPT? 😭 The only released downloadable version unless you package it yourself is on the [discord server](https://discord.gg/M4xxbhzEWU).

i did that same issue
