### ISSUE TITLE
OK i know i made one before but i followed all the instructions and no chatgpt this time

### ISSUE THREAD

**Issue by KingOreoTheThird** [GlitchyTurtle/Avatar-Addon#11]
I download version 1.20.10 from the page as my Minecraft is the education edition, and it doesn't support releases beyond 1.20.13. After entering the game, it says that I now have bending (arrows not in offhand), but nothing actually happens—no commands, nothing. Just a resistance to bending like an enchanted book. I've experimented with various releases and attempted numerous fixes. At this point, I'm considering giving up. Please help.

AND I DID DOWNLOAD FROM DISCORD

**Comment by GlitchyTurtle** [comment]
Can you message me on discord? It’s a lot nicer than GitHub issues.

**Comment by KingOreoTheThird** [comment]
> Can you message me on discord? It’s a lot nicer than GitHub

I went on discord and asked someone explained to me that because of advanced modding features being removed from education so I used a mod that allows me to enable them so basically if you don't have this mod it wont work becus the mod relys on apis a lot anyway great mod
