### ISSUE TITLE
Addon wont work on relms 

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [GlitchyTurtle/Avatar-Addon#2]
Hello when i try to use this addon on realms none of the bending works

**Comment by GlitchyTurtle** [comment]
Is experimental gameplay enabled? Be sure you have all the ones except the caves and cliffs toggle, which is optional.

**Comment by GlitchyTurtle** [comment]
If you attempt to apply a new pack to your realm utilizing the Gametest API then it will basically get rejected.

There is literally no ETA as to when the development team at Mojang will reinstate this so asking will not bring answers.

BDS is confirmed to be working just fine with Gametest so if your pack that is utilizing the Gametest API is extremely vital to have in your world then I would suggest switching from Realms to BDS until this dilemma is rectified by their development team.
