### ISSUE TITLE
Not showing up/transfering in minecraft 

### ISSUE THREAD

**Issue by Mithique** [GlitchyTurtle/Avatar-Addon#3]
![Screenshot_20220623-040005_My Files](https://user-images.githubusercontent.com/108059433/175262247-378797d8-4405-400f-8c3f-3abf2d4a7f07.jpg)
Doesn't go to minecraft. Am I doing it wrong? Don't see it in my RP or BP and when I click on it to open or download it says I don't have any apps that can open it (my minecraft is updated to the latest version) is there a folder in minecraft I can put it in or is there a app/file manager that I need to process the file

**Comment by GlitchyTurtle** [comment]
Hmm, that's an odd bug. It appears you are one of the few to have it, if not the only one. I'll see if I can package the addon differently, each pack individually. You might have to wait till the next update, as I want to stay focused entirely on that for now!
