### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by estidley** [GlitchyTurtle/Avatar-Addon#4]
![Screenshot_20220708-024720_Minecraft](https://user-images.githubusercontent.com/36413107/177943898-d8a30e0d-b08d-43db-8a48-33a88bb53285.jpg)
![Screenshot_20220708-024726_Minecraft](https://user-images.githubusercontent.com/36413107/177943900-6709c4a7-c551-48b8-837f-b92563026e0e.jpg)

Tried using the "/function choose" command but I get this error.

**Comment by estidley** [comment]
I was able to find the bending book however there is an issue with the textures
![Screenshot_20220708-030034_Minecraft](https://user-images.githubusercontent.com/36413107/177946022-f1348d73-d116-4ed9-a4a5-517785013066.jpg)
![Screenshot_20220708-030116_Minecraft](https://user-images.githubusercontent.com/36413107/177946093-4f7db1fb-083b-464b-94c6-8ee7717a5cda.jpg)

**Comment by GlitchyTurtle** [comment]
First, /function choose won’t work anymore. Use !scroll or /function scroll.

Second, the scroll is missing the textures because you have not applied the texture pack!

**Comment by estidley** [comment]
Thanks! I see that now. Still has the old way on the readme though. Where can I find the texture pack?

**Comment by GlitchyTurtle** [comment]
Is there a download yet on GitHub? It might have already been downloaded as a .mcaddon, but check the discord for the newer version.
