### ISSUE TITLE
Not working on education edition

### ISSUE THREAD

**Issue by ForgetMe1** [GlitchyTurtle/Avatar-Addon#5]
I saw this mod and thought it was really cool. I wanted to download it to play with my friends but when I downloaded it, the behaviour pack didn’t download. This is what it said “ Required '/modules/0/version' element is the wrong type in pack manifest.” i really wanted to play this mod so I hope you can fix it.

**Comment by GlitchyTurtle** [comment]
This is because you have an outdated version - Mojang recently made some changes to how gametest is declared in the manifest. All you have to do is download the most recent version: https://mcpedl.com/avatar-addon-vanilla-addon-1/
Have fun playing with your friends!
