### ISSUE TITLE
Not working with another mod

### ISSUE THREAD

**Issue by DerpyGrimReaper** [GlitchyTurtle/Avatar-Addon#6]
I have another mod that also uses a bar, but I can’t use both at the same time because they have the same name root_panel/trait_cooldown_bar I was wandering if there was any way you could change the name slightly or something, but if it is not possible that’s alright

**Comment by GlitchyTurtle** [comment]
I’ll change the name for sure! Although I can’t promise there won’t be other compatibility issues.
